### ISSUE TITLE
Dependencies resolution problem

### ISSUE THREAD

**Issue by MuhammadAasharibNawshad** [sign-language-processing/pose-to-video#5]
Hello,

This repo donot have freezed dependencies which is causing the dependencies resolution and code running issues. Since many of the the latest packages have updated, ideal solution will be to freeze the dependencies on which video generation is working. Also please specify the python version for smooth dependency resolution.

Thanks,

**Comment by AmitMY** [comment]
What issues are you encountering?

**Comment by MuhammadAasharibNawshad** [comment]
for running the project i first i create conda env with python 3.9 then i run `pip install .` 

Then I try to run pix2pix and controlnet method using the commands given. but They do not run and give error module not found. for solving this issue I install the required package and then again run the command but again get some other module not found error. this goes on and on...

Further, tensorflow, torch versions are very specific with cuda version. these things also need to be defined as installing latest version of packages are causing cuda incompatibility and other libraries issues. 

I think the solution is to freeze the packages version.

**Comment by AmitMY** [comment]
You should follow the README.
For example, if you would like to run `pix2pix`, you must: `pip install '.[pix2pix]'`

If you have a specific error, for example you say "module not found", please write THE FULL ERROR here. which module not found? What commands are you running exactly?

**Comment by MuhammadAasharibNawshad** [comment]
Loading input pose ...
Generating video ...
2024-05-16 09:20:06.097602: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-16 09:20:07.040754: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\aasha\.conda\envs\p_to_v\Scripts\pose_to_video.exe\__main__.py", line 7, in <module>
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\pose_to_video\bin.py", line 63, in main
    for frame in tqdm(frames):
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\pose_to_video\conditional\pix2pix\__init__.py", line 40, in pose_to_video
    model = load_model(model_path, compile=False)
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\keras\src\saving\saving_api.py", line 183, in load_model
    return legacy_h5_format.load_model_from_hdf5(
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\keras\src\legacy\saving\legacy_h5_format.py", line 133, in load_model_from_hdf5
    model = saving_utils.model_from_config(
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\keras\src\legacy\saving\saving_utils.py", line 85, in model_from_config
    return serialization.deserialize_keras_object(
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\keras\src\legacy\saving\serialization.py", line 495, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\keras\src\models\model.py", line 517, in from_config
    return functional_from_config(
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\keras\src\models\functional.py", line 517, in functional_from_config
    process_layer(layer_data)
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\keras\src\models\functional.py", line 497, in process_layer
    layer = saving_utils.model_from_config(
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\keras\src\legacy\saving\saving_utils.py", line 85, in model_from_config
    return serialization.deserialize_keras_object(
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\keras\src\legacy\saving\serialization.py", line 495, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\keras\src\layers\core\wrapper.py", line 43, in from_config
    layer = serialization_lib.deserialize_keras_object(
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\keras\src\saving\serialization_lib.py", line 694, in deserialize_keras_object
    cls = _retrieve_class_or_fn(
  File "C:\Users\aasha\.conda\envs\p_to_v\lib\site-packages\keras\src\saving\serialization_lib.py", line 812, in _retrieve_class_or_fn
    raise TypeError(
TypeError: Could not locate class 'Sequential'. Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()`. Full object config: {'class_name': 'Sequential', 'config': {'name': 'sequential_2', 'layers': [{'class_name': 'InputLayer', 'config': {'batch_input_shape': [None, 256, 256, 3], 'dtype': 'float32', 'sparse': False, 'ragged': False, 'name': 'conv2d_1_input'}}, {'class_name': 'Conv2D', 'config': {'name': 'conv2d_1', 'trainable': True, 'dtype': 'float32', 'filters': 64, 'kernel_size': [4, 4], 'strides': [2, 2], 'padding': 'same', 'data_format': 'channels_last', 'dilation_rate': [1, 1], 'groups': 1, 'activation': 'linear', 'use_bias': False, 'kernel_initializer': {'class_name': 'RandomNormal', 'config': {'mean': 0.0, 'stddev': 0.02, 'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}}, {'class_name': 'LeakyReLU', 'config': {'name': 'leaky_re_lu_1', 'trainable': True, 'dtype': 'float32', 'alpha': 0.30000001192092896}}]}}

**Comment by sparkkid1234** [comment]
hi @AmitMY firstly thank you for open-sourcing this but I did encounter the same exact dependencies resolution problem @MuhammadAasharibNawshad encountered. 

I did manage to fix it and am relaying my findings here for future reference. The main problem is with the `keras` model loading. It seems like the models were trained using tensorflow 2.10.0 (based on the docker image) which uses keras 2.x.x while the latest tensorflow 2.16.0 uses keras 3.x.x which leads to the code breaking when trying to load the model. @MuhammadAasharibNawshad you can fix this by using any version of tensorflow with keras 2.x.x, so far I can confirm TF 2.10.0 -> 2.15.0 all works.

**Comment by AmitMY** [comment]
Thanks for the information @sparkkid1234 !

**Comment by Tortoise17** [comment]
@AmitMY tensorflow current release 2,16,x has no available packages. while downgrade to 2,14,x also doesn't provide the proper export of results.
